"""
Django settings for ipm project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv

import pytz
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from funcoes.utilitarios import loga_mensagem

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-o$1r4)2fb^f^x%8ywzuql0xkuu2=88zo*yt3n@6$gr3cd(^(5)"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.7.147.245', '127.0.0.1', 'srv-xipmprod01.economia.go.gov.br',
                 'localhost']


# Application definition

INSTALLED_APPS = [
    "polls.apps.PollsConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ipm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ipm.wsgi.application"

DATABASE_ROUTERS = ['ipm.routers.MeuRoteador']

# Carrega as variáveis de ambiente do arquivo .env
load_dotenv(verbose=True, encoding='latin-1')

# Configuração do Banco de Dados Oracle
host = os.getenv('DB_ORACLE_HOST')
port = os.getenv('DB_ORACLE_PORT')
service_name = os.getenv('DB_ORACLE_DATABASE')
dns_name_oracle = f'(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = {host})(PORT = {port})) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = {service_name})))'

# Configuração do Banco de Dados Oracle X9
host = os.getenv('DB_ORACLE_X9_HOST')
port = os.getenv('DB_ORACLE_X9_PORT')
service_name = os.getenv('DB_ORACLE_X9_DATABASE')
dns_name_oracle_x9 = f'(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = {host})(PORT = {port})) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = {service_name})))'

# Configuração do Banco de Dados Oracle DW
host = os.getenv('DB_ORACLE_DW_HOST')
port = os.getenv('DB_ORACLE_DW_PORT')
service_name = os.getenv('DB_ORACLE_DW_DATABASE')
dns_name_oracle_dw = f'(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = {host})(PORT = {port})) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = {service_name})))'

oracle_config = {
    'ENGINE': 'django.db.backends.oracle',
    'NAME': dns_name_oracle,
    'USER': os.getenv('DB_ORACLE_USERNAME'),
    'PASSWORD': os.getenv('DB_ORACLE_PASSWORD'),
}

DATABASES = {
    'default': oracle_config,
    'oracle': oracle_config,
    'oracle_x9': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': dns_name_oracle_x9,
        'USER': os.getenv('DB_ORACLE_X9_USERNAME'),
        'PASSWORD': os.getenv('DB_ORACLE_X9_PASSWORD'),
    },
    'oracle_dw': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': dns_name_oracle_dw,
        'USER': os.getenv('DB_ORACLE_DW_USERNAME'),
        'PASSWORD': os.getenv('DB_ORACLE_DW_PASSWORD'),
    }
}

loga_mensagem(f"""String de Conexão Oracle..: NAME: {dns_name_oracle} - USER: {DATABASES['oracle']['USER']}""")
loga_mensagem(f"""String de Conexão Oracle X9..: NAME: {dns_name_oracle_x9} - USER: {DATABASES['oracle_x9']['USER']}""")
loga_mensagem(f"""String de Conexão Oracle DW..: NAME: {dns_name_oracle_dw} - USER: {DATABASES['oracle_dw']['USER']}""")

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = False

LOCAL_TZ = pytz.timezone(os.getenv('LOCAL_TZ'))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


from django.db import connection

